
# 端口
server.port=8080

# PostgreSQL 连接配置
spring.datasource.url=jdbc:postgresql://localhost:5432/server_exp
spring.datasource.username=postgres
spring.datasource.password=Wj686866
spring.datasource.driver-class-name=org.postgresql.Driver

# MyBatis-Plus 配置
mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
mybatis-plus.global-config.db-config.id-type=auto
spring.sql.init.mode=never
# Redis 配置（第七周实验必须）
spring.data.redis.host=127.0.0.1
spring.data.redis.port=6379
spring.data.redis.database=0
spring.data.redis.timeout=3000



# JWT 配置（实验9）
security.jwt.secret=demo-jwt-secret-key-for-spring-security-2026
security.jwt.expiration-millis=7200000
